workflows:
  ios_build:
    name: Build iOS IPA (No Codesign)
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default

    scripts:
      - name: Install dependencies
        script: flutter pub get

      - name: Build iOS app (no codesign)
        script: |
          flutter build ios --release --no-codesign
          cd build/ios/iphoneos
          mkdir -p Payload
          cp -r Runner.app Payload/
          zip -r ../../ios_build_output.zip Payload

    artifacts:
      - build/ios/ios_build_output.zip
