workflows:
  ios_build:
    name: Build iOS IPA (No Codesign)
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default

    scripts:
      - name: Install dependencies
        script: |
          flutter pub get

      - name: Build iOS IPA
        script: |
          flutter build ipa --release --no-codesign

      - name: Collect IPA into ./artifacts
        script: |
          set -e
          echo "=== Searching for any .ipa file ==="
          FOUND_IPA="$(find "$PWD" -type f -name "*.ipa" | head -n 1 || true)"
          echo "FOUND_IPA=$FOUND_IPA"
          mkdir -p artifacts
          if [ -n "$FOUND_IPA" ]; then
            cp "$FOUND_IPA" artifacts/Runner.ipa
            echo "Copied IPA to artifacts/Runner.ipa"
          else
            echo "No .ipa found, zipping iOS build output as fallback"
            (cd build/ios && zip -r ../ios_build_output.zip . || true)
            if [ -f build/ios_build_output.zip ]; then
              mv build/ios_build_output.zip artifacts/
            fi
          fi
          echo "=== Listing artifacts folder ==="
          ls -al artifacts || true

      - name: Optional: make a direct download URL (transfer.sh)
        script: |
          set +e
          if [ -f artifacts/Runner.ipa ]; then
            echo "Uploading artifacts/Runner.ipa to transfer.sh..."
            URL=$(curl -s --upload-file artifacts/Runner.ipa https://transfer.sh/Runner.ipa)
            echo "Direct download (valid for ~14 days):"
            echo "$URL"
          else
            echo "No Runner.ipa to upload."
          fi

    artifacts:
      - "artifacts/**"

    publishing:
      email:
        recipients:
          - jonteawe@gmail.com
