name: knb_capture
description: A color capture and analysis tool for KnB Studio.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Kamera + sensorer
  camera: ^0.10.5
  sensors_plus: ^5.0.0

  # Filsystem & sökvägar
  path: ^1.8.3
  path_provider: ^2.1.1

  # Bildhantering (valfritt om du exporterar)
  image_picker: ^1.0.4

  # --- Firebase ---
  firebase_core: ^3.0.0
  firebase_auth: ^5.0.0
  cloud_firestore: ^5.0.0
  firebase_storage: ^12.0.0
  firebase_auth: ^5.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
