// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA-0f8D8-0OVeWcz_HNM005vx6DogC-Olw',
    appId: '1:35962282921:web:b82037adad5e59e9669ab8',
    messagingSenderId: '35962282921',
    projectId: 'knbcapturecloud',
    authDomain: 'knbcapturecloud.firebaseapp.com',
    storageBucket: 'knbcapturecloud.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDKxWQk87VjINdKH--njn2abt7fcOzgK1g',
    appId: '1:35962282921:android:67b038ed74d4245a669ab8',
    messagingSenderId: '35962282921',
    projectId: 'knbcapturecloud',
    storageBucket: 'knbcapturecloud.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBU9z3TQ3zjKDlBni_6Ok0_zB8a5rYP4M4',
    appId: '1:35962282921:ios:a3ce04b988534c08669ab8',
    messagingSenderId: '35962282921',
    projectId: 'knbcapturecloud',
    storageBucket: 'knbcapturecloud.appspot.com',
    iosBundleId: 'com.example.knbCapture',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBU9z3TQ3zjKDlBni_6Ok0_zB8a5rYP4M4',
    appId: '1:35962282921:ios:a3ce04b988534c08669ab8',
    messagingSenderId: '35962282921',
    projectId: 'knbcapturecloud',
    storageBucket: 'knbcapturecloud.appspot.com',
    iosBundleId: 'com.example.knbCapture',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA-0f8D8-0OVeWcz_HNM005vx6DogC-Olw',
    appId: '1:35962282921:web:12f5c2ba94fd5b47669ab8',
    messagingSenderId: '35962282921',
    projectId: 'knbcapturecloud',
    authDomain: 'knbcapturecloud.firebaseapp.com',
    storageBucket: 'knbcapturecloud.appspot.com',
  );
}
